version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "bundle exec rails db:create db:schema:load && bundle exec rspec"]
    volumes:
      - ".:/rails"
    depends_on:
      - db
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://user:password@db:5432/game_of_life_test
    networks:
      - app-network

  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game_of_life_test
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
