version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ".:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/game_of_life_development
    networks:
      - app-network

  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game_of_life_development
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
